name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: andrewdyer/github-workflows/.github/workflows/build.yml@main
    with:
      package-manager: yarn

  test-unit:
    uses: andrewdyer/github-workflows/.github/workflows/test.yml@main
    needs: build
    with:
      package-manager: yarn

  test-e2e:
    uses: andrewdyer/github-workflows/.github/workflows/playwright.yml@main
    needs: build
    with:
      package-manager: yarn

  typecheck:
    uses: andrewdyer/github-workflows/.github/workflows/type-check.yml@main
    needs: build
    with:
      package-manager: yarn
