name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: andrewdyer/github-workflows/.github/workflows/build.yml@main
    with:
      package-manager: yarn

  test:
    uses: andrewdyer/github-workflows/.github/workflows/test.yml@main
    with:
      package-manager: yarn

  typecheck:
    uses: andrewdyer/github-workflows/.github/workflows/type-check.yml@main
    with:
      package-manager: yarn
